---
title: "MICE exercises"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

# Intro {.sidebar}

This dashboard covers the practical exercise materials for the [***Missing Data module in Survey Data Analysis***](https://osiris.uu.nl/osiris_student_uuprd/OnderwijsCatalogusSelect.do?selectie=cursus&collegejaar=2022&cursus=201300001&taal=nl)

---

Module instructors: <br>
[Stef van Buuren](https://www.stefvanbuuren.name) and [Gerko Vink](https://www.gerkovink.com) <br>

---

| When? | What?        | Where? |
|-------|--------------|--------|
| Wk 45 | Exercise 1-3 | offline |
| Wk 46 | Exercise 4-6 | offline |

---

# Wk 45: 4-8 Nov

## Column 1

### Screen share for the back of the room

[use this link to get there](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NTcxNTBkMDEtNzljNy00NTk4LWExOWItM2UxNzFkMWJmODJh%40thread.v2/0?context=%7b%22Tid%22%3a%22d72758a0-a446-4e0f-a0aa-4bf95a4a10e7%22%2c%22Oid%22%3a%22cc7d7fcd-73aa-4668-936a-2ca38cace0f3%22%7d)

### Exercises for this week

The following exercises are walkthroughs that take you through the process of drawing valid inferences from incomplete data sets with `mice` in `R`. 

- [1. Ad Hoc methods and the mice algorithm](https://www.gerkovink.com/newVignettes/1AdHoc/Adhoc_methods_and_mice.html)
- [2. Convergence and pooling](https://www.gerkovink.com/newVignettes/2ConvPool/Convergence_and_pooling.html)
- [3. Inspecting how the observed data and missingness are related](https://www.gerkovink.com/newVignettes/3Inspect/The_imputation_and_nonresponse_models.html)

### Discussion of Exercises

If you struggle with the exercises, feel free to ask us for any help. We also have the following video walkthroughs for these exercises. Disclaimer: these walkthroughs are a few years old and `mice` is work in progress. This means that the general chain of thought is still identical, but that individual results or imputed values may have changed because of improvements to the internal sampler functions. 

- [Exercise 1 walkthrough](https://www.dropbox.com/s/cb2yptcr6dfv0u8/Exercise%201.mp4?dl=0)
- [Exercise 2 walkthrough](https://www.dropbox.com/s/2118fbiirf91mq0/Exercise%202.mp4?dl=0)
- [Exercise 3 walkthrough](https://www.dropbox.com/s/77ckcmwjy82wl9w/Exercise%203.mp4?dl=0)

# Wk 46: 11-15 Nov

## Column 1

### Exercises for this week

The following exercises are walkthroughs that take you through the process of drawing valid inferences from incomplete data sets with `mice` in `R`. 

- [4. Passive imputation and post-processing](https://www.gerkovink.com/newVignettes/4PassivePostProcess/Passive_imputation_and_Post-processing.html)
- [5. Combining inferences](https://www.gerkovink.com/newVignettes/5CombInference/CombiningInferences.html)
- [6. Generating synthetic data with high utility using `mice`](https://www.gerkovink.com/newVignettes/10Synthetic/synthetic.html)

### Discussion of Exercises

If you struggle with the exercises, feel free to ask us for any help. We also have the following video walkthroughs for these exercises. Disclaimer: these walkthroughs are a few years old and `mice` is work in progress. This means that the general chain of thought is still identical, but that individual results or imputed values may have changed because of improvements to the internal sampler functions. 

- [Exercise 4 walkthrough](https://www.dropbox.com/s/9u9ncf1qgxj3g9u/Exercise%204.mp4?dl=0)
- [Exercise 5 walkthrough](https://www.dropbox.com/s/9ykzcci5kf5lguw/Exercise%205.mp4?dl=0)
